import { logger } from '../../utils/logger';
import DatabaseService from '../DatabaseService';
import type { TrainingInteraction, FrequentPattern } from '../../types';
import { PatternAnalyzer } from './PatternAnalyzer';

/**
 * AI Learning - Knowledge Generator Module
 *
 * Responsible for:
 * - Generating knowledge base entry suggestions from patterns
 * - Auto-updating knowledge base with high-confidence entries
 * - Content generation from successful interactions
 * - Category classification and confidence scoring
 */
export class KnowledgeGenerator {
  private static instance: KnowledgeGenerator;

  private constructor() {}

  public static getInstance(): KnowledgeGenerator {
    if (!KnowledgeGenerator.instance) {
      KnowledgeGenerator.instance = new KnowledgeGenerator();
    }
    return KnowledgeGenerator.instance;
  }

  /**
   * Sugiere nuevas entradas para la knowledge base basado en patrones
   */
  public async suggestKnowledgeBaseEntries(): Promise<
    Array<{
      title: string;
      content: string;
      keywords: string[];
      category: string;
      confidence: number;
      frequency: number;
      reasoning: string;
    }>
  > {
    try {
      logger.info('💡 Generating knowledge base suggestions from learning data');

      const patternAnalyzer = PatternAnalyzer.getInstance();
      const patterns = await patternAnalyzer.analyzeFrequentPatterns(20);
      const suggestions: Array<{
        title: string;
        content: string;
        keywords: string[];
        category: string;
        confidence: number;
        frequency: number;
        reasoning: string;
      }> = [];

      for (const pattern of patterns) {
        // Solo sugerir para patrones con baja satisfacción o alta frecuencia
        if (
          pattern.frequency >= 3 &&
          (pattern.averageSuccessScore < 0.7 || pattern.frequency >= 10)
        ) {
          const suggestedEntry = await this.generateKnowledgeEntrySuggestion(pattern);

          if (suggestedEntry) {
            const confidence = this.calculateSuggestionConfidence(pattern);

            suggestions.push({
              ...suggestedEntry,
              confidence,
              frequency: pattern.frequency,
              reasoning: this.generateSuggestionReasoning(pattern),
            });
          }
        }
      }

      // Ordenar por confianza y frecuencia
      suggestions.sort((a, b) => b.confidence * b.frequency - a.confidence * a.frequency);

      logger.info(`💡 Generated ${suggestions.length} knowledge base suggestions`);
      return suggestions.slice(0, 10); // Limitar a 10 sugerencias más relevantes
    } catch (error) {
      logger.error('Error generating knowledge base suggestions:', error);
      return [];
    }
  }

  /**
   * Actualiza automáticamente la knowledge base con sugerencias aprobadas
   */
  public async autoUpdateKnowledgeBase(
    confidence: number = 0.8,
    frequency: number = 5
  ): Promise<void> {
    try {
      logger.info(
        `🔄 Auto-updating knowledge base (confidence >= ${confidence}, frequency >= ${frequency})`
      );

      const suggestions = await this.suggestKnowledgeBaseEntries();
      let addedEntries = 0;

      for (const suggestion of suggestions) {
        if (suggestion.confidence >= confidence && suggestion.frequency >= frequency) {
          // Verificar que no exista ya una entrada similar
          const existingEntries = await DatabaseService.searchKnowledgeBase(suggestion.title);

          if (existingEntries.length === 0) {
            const success = await DatabaseService.addKnowledgeBase({
              title: suggestion.title,
              content: suggestion.content,
              keywords: suggestion.keywords.join(', '),
              category: suggestion.category,
              priority: 'medium',
              isActive: true,
              source: 'auto_learning',
              metadata: {
                autoGenerated: true,
                confidence: suggestion.confidence,
                frequency: suggestion.frequency,
                reasoning: suggestion.reasoning,
                generatedAt: new Date().toISOString(),
              },
            });

            if (success) {
              addedEntries++;
              logger.info(
                `✅ Auto-added knowledge entry: "${suggestion.title}" (confidence: ${suggestion.confidence.toFixed(3)})`
              );
            }
          } else {
            logger.debug(`⏭️ Skipping similar entry: "${suggestion.title}"`);
          }
        }
      }

      logger.info(`🎉 Auto-update completed. Added ${addedEntries} new knowledge base entries`);
    } catch (error) {
      logger.error('Error in auto knowledge base update:', error);
    }
  }

  /**
   * Generate knowledge entry suggestion from frequent pattern
   */
  public async generateKnowledgeEntrySuggestion(
    pattern: FrequentPattern,
    interactions?: TrainingInteraction[]
  ): Promise<
    | {
        title: string;
        content: string;
        keywords: string[];
        category: string;
      }
    | undefined
  > {
    try {
      // Si el patrón tiene muy buena puntuación, no necesita mejora
      if (pattern.averageSuccessScore > 0.8) {
        return undefined;
      }

      // Get interactions if not provided
      if (!interactions) {
        const patternAnalyzer = PatternAnalyzer.getInstance();
        const allInteractions = await DatabaseService.getTrainingInteractions(500);
        interactions = allInteractions.filter(i =>
          patternAnalyzer.extractMessagePatterns(i.userMessage).includes(pattern.pattern)
        );
      }

      if (interactions.length === 0) {
        return undefined;
      }

      // Analizar el contexto de las interacciones para generar sugerencia
      const patternAnalyzer = PatternAnalyzer.getInstance();
      const commonIntents = patternAnalyzer.extractCommonIntents(interactions);
      const commonKeywords = patternAnalyzer.extractCommonKeywords(interactions);

      const category = patternAnalyzer.categorizePattern(pattern.pattern, commonIntents);

      if (category === 'unknown') {
        return undefined;
      }

      const suggestion = {
        title: this.generateTitle(pattern.pattern, category),
        content: await this.generateContent(pattern.pattern, interactions, category),
        keywords: commonKeywords,
        category,
      };

      return suggestion;
    } catch (error) {
      logger.error('Error generating knowledge entry suggestion:', error);
      return undefined;
    }
  }

  /**
   * Generate title for knowledge entry
   */
  public generateTitle(pattern: string, category: string): string {
    const categoryTitles: Record<string, string> = {
      pricing: `Información sobre ${pattern}`,
      services: `Detalles del servicio de ${pattern}`,
      schedule: `Horarios para ${pattern}`,
      location: `Ubicación y ${pattern}`,
      contact: `Contacto para ${pattern}`,
      greetings: `Respuesta a ${pattern}`,
      support: `Soporte para ${pattern}`,
      general: `Información general sobre ${pattern}`,
    };

    return categoryTitles[category] || `Información sobre ${pattern}`;
  }

  /**
   * Generate content for knowledge entry based on successful interactions
   */
  public async generateContent(
    pattern: string,
    interactions: TrainingInteraction[],
    _category: string
  ): Promise<string> {
    // Generar contenido basado en las respuestas exitosas
    const successfulInteractions = interactions.filter(i => i.successScore > 0.7);

    if (successfulInteractions.length === 0) {
      return `Información detallada sobre ${pattern} que aborda las consultas frecuentes de los usuarios.`;
    }

    // Analizar respuestas exitosas para extraer patrones
    const commonResponses = successfulInteractions.map(i => i.aiResponse);
    const patternAnalyzer = PatternAnalyzer.getInstance();
    const commonPhrases = patternAnalyzer.extractCommonPhrases(commonResponses);

    return `${commonPhrases.slice(0, 3).join(' ')} Para más información específica sobre ${pattern}, un especialista podrá ayudarte con todos los detalles.`;
  }

  /**
   * Calculate confidence score for knowledge base suggestion
   */
  public calculateSuggestionConfidence(pattern: FrequentPattern): number {
    let confidence = 0.5; // Base

    // Mayor frecuencia = mayor confianza
    if (pattern.frequency >= 10) confidence += 0.3;
    else if (pattern.frequency >= 5) confidence += 0.2;
    else if (pattern.frequency >= 3) confidence += 0.1;

    // Menor score promedio = mayor necesidad de mejora
    if (pattern.averageSuccessScore < 0.5) confidence += 0.3;
    else if (pattern.averageSuccessScore < 0.7) confidence += 0.2;

    // Recency factor
    const daysSinceLastSeen = (Date.now() - pattern.lastSeen.getTime()) / (1000 * 60 * 60 * 24);
    if (daysSinceLastSeen < 7) confidence += 0.1;

    return Math.min(confidence, 1.0);
  }

  /**
   * Generate reasoning text for knowledge base suggestion
   */
  public generateSuggestionReasoning(pattern: FrequentPattern): string {
    const reasons: string[] = [];

    if (pattern.frequency >= 10) {
      reasons.push('Patrón muy frecuente');
    } else if (pattern.frequency >= 5) {
      reasons.push('Patrón frecuente');
    }

    if (pattern.averageSuccessScore < 0.5) {
      reasons.push('Baja satisfacción del usuario');
    } else if (pattern.averageSuccessScore < 0.7) {
      reasons.push('Satisfacción mejorable');
    }

    const daysSince = (Date.now() - pattern.lastSeen.getTime()) / (1000 * 60 * 60 * 24);
    if (daysSince < 7) {
      reasons.push('Consulta reciente');
    }

    return reasons.join(', ');
  }

  /**
   * Check if knowledge base entry already exists
   */
  public async checkExistingEntry(title: string): Promise<boolean> {
    try {
      const existingEntries = await DatabaseService.searchKnowledgeBase(title);
      return existingEntries.length > 0;
    } catch (error) {
      logger.error('Error checking existing knowledge base entry:', error);
      return false;
    }
  }

  /**
   * Add knowledge base entry
   */
  public async addKnowledgeBaseEntry(entry: {
    title: string;
    content: string;
    keywords: string;
    category: string;
    priority?: 'low' | 'medium' | 'high' | number;
    isActive?: boolean;
    source?: string;
    metadata?: any;
  }): Promise<boolean> {
    try {
      return await DatabaseService.addKnowledgeBase({
        priority: 'medium' as const,
        isActive: true,
        source: 'ai_learning',
        ...entry,
      });
    } catch (error) {
      logger.error('Error adding knowledge base entry:', error);
      return false;
    }
  }

  /**
   * Search knowledge base entries
   */
  public async searchKnowledgeBase(query: string): Promise<any[]> {
    try {
      return await DatabaseService.searchKnowledgeBase(query);
    } catch (error) {
      logger.error('Error searching knowledge base:', error);
      return [];
    }
  }
}

export default KnowledgeGenerator.getInstance();
